### ISSUE TITLE
Support transports without ports

### ISSUE THREAD

**Issue by jerith** [twisted/klein#102]
Currently, Klein calls `request.getHost().port` (see https://github.com/twisted/klein/blob/master/src/klein/resource.py#L77-L81 ) to get the port number to add to the server name. Unfortunately, if the `IAddress` returned by `request.getHost()` doesn't have a `port` attribute (if it's from a loopback transport or a unix socket, for example) it breaks.

A possible solution is to check for a `port` attribute or catch an `AttributeError` instead of just assuming it's there. :-)

**Comment by InfoSec812** [comment]
I fixed this in #103. Hopefully it will get merged soon.

**Comment by jerith** [comment]
Fixed in #103.
