### ISSUE TITLE
Return HTTP status code 204 for empty response

### ISSUE THREAD

**Issue by rgov** [twisted/klein#104]
Would it be sensible to change the status code from 200 OK to 204 No Content without having to explicitly call `request.setResponseCode(204)` when the response body is empty?

**Comment by vanHoesel** [comment]
Depending on what the context is, I just stumbled upon this question here...

204 is meant for a specific purpose... Confirm that the request has been understood and could be processed accordingly!

Use it for confirmation of UI actions, like tick boxes that get immediately sent to the backend, star-ratings, row deletions from a table.

204 Also implies that the browser will not update the view.

===

If however it is a response to a search or a resource that has no children... then return an empty list (how ever that is defined, depending if it is a XML doc or JSON struct) ... if that means an empty word list, then yes, no lines and Content-Length = 0.

But still 200 OK

You do want to have the browser point to the new page with the new result list.

**Comment by wsanchez** [comment]
Please no.

It is not incorrect for a method to return an empty response body with a status code of `200`, so the framework should not be "fixing" that for you.

**Comment by rgov** [comment]
Fair enough.
