### ISSUE TITLE
Another Example Route: catch all

### ISSUE THREAD

**Issue by BenjamenMeyer** [twisted/klein#110]
It would be helpful to have an example of a catch all route, one that uses the Werkzeug's `PathConverter`.  The information can be found if dug deep enough, but having examples makes everyone's life easier.

**Comment by notoriousno** [comment]
Do you have examples?  I agree that the documentation is lacking and should contain more than it does.  I'm working on my own set of documentation improvements in my spare time (which is always dwindling).  I'll get a blog post out one of these days :).

My documentation improvement repo: https://github.com/notoriousno/klein-basics

**Comment by BenjamenMeyer** [comment]
For the purposes of Klein, it could be simpler. I needed it due to https://github.com/BenjamenMeyer/mimic/blob/bugfix_swift_object_paths/mimic/rest/swift_api.py#L304 and fixing a bug in the Mimic project.

As another example (outside of Twisted and Klein) - https://falcon.readthedocs.io/en/stable/api/api.html#falcon.API.add_sink Falcon has some good examples of how to use their various tooling. Doing something similar and appropriate for Klein would be beneficial.

**Comment by notoriousno** [comment]
ahh ok I thought you had an example of a function like ``add_sink()`` using Werkzeug.  Sorry misread your post.  Definitely needs to be in the docs, maybe the error handling page.

**Comment by BenjamenMeyer** [comment]
Thanks, PR #115 looks great.

**Comment by notoriousno** [comment]
With all the activity in recent days with this project, I decided to do some work on it on my day off.  While looking over the docstrings for ``handle_errors``, I found this little gem https://github.com/twisted/klein/blob/master/src/klein/app.py#L275.  Catching ``werkzeug.exceptions.NotFound`` essentially nullifies #115 as it stands now D'oh!  If anything this is more justification for the fact that the documentation could use some love.

**Comment by glyph** [comment]
Looks like #115 fixed it!

**Comment by BenjamenMeyer** [comment]
@notoriousno just catching up...

First and foremost...Thanks for solving this.

Second, it doesn't matter whether `branch=True` or not, the `werkzeug.exceptions.NotFound` is not a replacement for the sink. What I'm requesting (and can be exemplified in the code I referenced) is completely separate from an underlying resource not being found (non-existent).

The purpose of the sink is to properly route the request; where `404 Not Found` is suppose to go back to the client in some form, not become an additional layer of logic for which the backend web developer needs to catch and redirect on.

Your example is beautiful in its simplicity and shows exactly how to use the sink.

All said...let's not confuse them.

Thanks again for solving this!
