### ISSUE TITLE
Disabling tracebacks in response should be much easier

### ISSUE THREAD

**Issue by pawelmhm** [twisted/klein#112]
By default Klein displays tracebacks in 500 response if unhandled error occurs. This is ok and useful for debugging but I think there should be some optional argument for run() disabling tracebacks and there should be information in documentation about this. 

Figuring out how to disable tracebacks in production is currently not obvious and requires you to go into Klein code find out it uses Site() object under the hood, find out this object has displayTraceback attribute and set this attribute to False on class level. 

So something like this:

``` python
from klein import Klein
from twisted.web.server import Site

app = Klein()
Site.displayTracebacks = False

@app.route('/')
def home(request):
    raise
    return 'Hello, world!'

app.run("localhost", 8080)
```

it would be better to simply have optional debug=True/False argument for `Klein().run()` that would set this for you.

**Comment by notoriousno** [comment]
I was actually thinking something similar a while back.  You have a much simpler approach than mine.  I took the approach of overloading ``Klein.run()`` and passing in ``Request``, ``Session``, and ``Site`` objects.

**Comment by wsanchez** [comment]
I think the whole idea of blatting tracebacks at clients is a bug…

**Comment by notoriousno** [comment]
It might be worth defaulting `displayTraceBacks = False` and use a flag/param to turn this feature on.
