### ISSUE TITLE
Unit test helpers

### ISSUE THREAD

**Issue by manishtomar** [twisted/klein#156]
There should be easy helpers to write unit tests that exercise the routing of the URLs. In other words, mimic's [`request`](https://github.com/rackerlabs/mimic/blob/7fef2fe53cead11f04a793dd971214247fadf94b/mimic/test/helpers.py#L156) and related functions should be part of klein.

**Comment by notoriousno** [comment]
This looks very interesting but I don't see any examples using mimic's request helper. How is this used and what does the ``testCase`` arg do? I've mostly been using ``mock`` to validate certain functions are executed. This is becoming a bit unwieldy and is susceptible to breaking. It would be nice if Klein had specific unit test tools comparable to Tornado and Flask.

**Comment by manishtomar** [comment]
Looks like `testCase` argument is not being used. The interesting bit is [`RequestTraversalAgent`](https://github.com/rackerlabs/mimic/blob/7fef2fe53cead11f04a793dd971214247fadf94b/mimic/test/helpers.py#L44) that takes a resource and calls request on that which happens to be Klein app's resource. This class should be there in klein. However, looks like it is copy-pasted from [treq](https://github.com/twisted/treq/blob/fcf5deb976c955ca6ef6484f414d25839932940e/src/treq/testing.py#L33). So I am guessing twisted would be the right place for this class? @glyph What are your thoughts?

**Comment by glyph** [comment]
We already moved these to a different project :) https://github.com/twisted/treq/blob/fcf5deb976c955ca6ef6484f414d25839932940e/src/treq/testing.py#L33

**Comment by glyph** [comment]
Since `request` is instantiating an HTTP _client_, `treq` is the right project.  The code moved from mimic _to_ `treq`, it was intentionally refactored upwards and not copy/pasted.

Klein may want to depend on treq for testing, or have some examples showing how to use treq for it.

**Comment by manishtomar** [comment]
> Since request is instantiating an HTTP client, treq is the right project.

Ok cool. I guess any project using klein can depend on treq for this class. I am fine closing this ticket then. @notoriousno are you ok with this resolution?

**Comment by notoriousno** [comment]
Yes I'm fine with the resolution, but I do believe, at the very minimum, there needs to be an example in the docs. Having ``treq`` as a dependency seems like overkill to me but certainly justified. I would label this ticket as an enhancement and allow someone to make a solution or document an example ;) Any volunteers?

I'll try this method out over the weekend as I will have some spare time, but I'm not 100% if I'll be able to write up an example doc anytime soon.

**Comment by glyph** [comment]
> at the very minimum, there needs to be an example in the docs

Oh yes, absolutely. treq needs a big narrative section explaining this, and klein should probably have a link to it.  I'll close this ticket, but feel free to file more PRs against treq.
