### ISSUE TITLE
Use unittest.mock whenever available

### ISSUE THREAD

**Issue by notoriousno** [twisted/klein#166]
Minor issue (almost trivial). Python 3 has a mock module built in and could  be used instead of requiring alternate packages.

``` python
try:
    from unittest.mock import MagicMock, patch
except ImportError:
    from mock import MagicMock, patch
```

This would eliminate 1 dependency and no exception would be raised.

**Comment by notoriousno** [comment]
As an alternative, a `requirements.txt` file can be provided specifically for unit tests. This can include things like `mock` or `six`.

**Comment by glyph** [comment]
There's a way to tell setup.py (and requirements.txt) that something is only required based on a specific Python version.  If you could fish this out of https://packaging.python.org I'd be most grateful :)

**Comment by notoriousno** [comment]
@glyoh This is why I have interns :) I'll take a look, I think I know what you're referring to.

**Comment by glyph** [comment]
Yeah, "environment markers", that's the ticket...

**Comment by jlitzingerdev** [comment]
I submitted a PR for this: https://github.com/twisted/klein/pull/221

I ran into this in a somewhat round about way.  I was trying to verify recent changes I'd made in twisted didn't break other twisted projects, only to find that mock never got installed.  Everything works fine when the tox setup is used, but this issue led me to believe a solution for cases not using tox was of interest.

**Comment by wsanchez** [comment]
#221 is merged, so… closing this out
