### ISSUE TITLE
Feature request: webargs support/parser

### ISSUE THREAD

**Issue by pgpbpadilla** [twisted/klein#169]
Not sure if this should be a requests for the [webargs](https://github.com/sloria/webargs) project or this one but here it is.

**Comment by wsanchez** [comment]
I don't think that's  appropriate for Klein.
In Klein you get a `request` argument, and `request.args` has the arguments.

**Comment by notoriousno** [comment]
It would be nice for klein to have some 3rd party support, so I encourage projects like webargs and will help in any shape if anyone is serious about it. The idea is not new, the project [shiji](https://github.com/williamsjj/shiji) has a similar `@webapi.json_arguments` decorator which I found useful in the past. However, like @wsanchez said this isn't an appropriate place for this request and should probably be placed in the webargs project.

**Comment by pgpbpadilla** [comment]
Somebody has implemented this, the webargs maintainers think it's best to release it as a separate package. 

Linking the PR for future reference: https://github.com/sloria/webargs/pull/159 

I guess I should close this request now. Please re-open if needed.
