### ISSUE TITLE
When rendering renderables, klein ought to emit a DOCTYPE.

### ISSUE THREAD

**Issue by glyph** [twisted/klein#18]
The documentation for twisted.web.template has a brief note on DOCTYPE declarations:

http://twistedmatrix.com/documents/current/web/howto/twisted-templates.html#auto9

Whoever renders some stuff with HTML in it, it's their job to insert an appropriate DOCTYPE and set an appropriate MIME type.  Maybe in your decorator you ought to be able to specify it somehow, but I think `<!DOCTYPE html>` is a good default.

**Comment by brighid** [comment]
Is this still a concern, and if so, is https://github.com/twisted/klein/blob/master/klein/resource.py#L213 the right place to start tweaking it?

**Comment by glyph** [comment]
@brighid yes, and yes. Thanks for asking! Please feel free to bother me when you have a PR :)
