### ISSUE TITLE
Need code example with async/await at reathedocs

### ISSUE THREAD

**Issue by rodrigc** [twisted/klein#207]
In https://github.com/twisted/klein/pull/151 coroutine support was added by @wsanchez to klein.
It would be nice to have a code example at https://klein.readthedocs.io/en/latest/
for using *async* / *await*.  Right now there is only an example using *Deferred*.

By the way, in https://github.com/twisted/twisted/pull/839 , I ported the rest of twisted.web to Python 3.

**Comment by wsanchez** [comment]
Here's an example: https://github.com/wsanchez/sample-klein-app/blob/master/src/sample_klein_app/application/dns.py
