### ISSUE TITLE
Twisted Klein 

### ISSUE THREAD

**Issue by DWDetrich** [twisted/klein#214]
Any twisting of muscles with elements is considered improper, especially with asynchronous programming. I find Klein to be unacceptable as a project.

**Comment by IlyaSkriblovsky** [comment]
Some context :)
https://github.com/rizsotto/Bear/issues/179
https://github.com/rhli/hadoop-EAR/issues/1

**Comment by twm** [comment]
I'm closing this as it doesn't seem to represent any work to be done on Klein.
