### ISSUE TITLE
All Python builds on all POSIX compliant OSes ... not written in ADA 95 or ADA 2014 etc ...

### ISSUE THREAD

**Issue by aspadistra** [twisted/klein#217]
So as to avoid posting this as a bug on all the open and closed source versions of Python out there ...

"They are all unreliable <rapVVares because..." 

All Python builds on all POSIX compliant OSes ... not written in ADA 95 or ADA 2014 etc ... 

ADA is about the only language save JAVA-bytecode that is not only OS safe but websafe ...

**Comment by twm** [comment]
I'm not quite sure what to make of this, but it doesn't seem to have anything to do with Klein. As such I am going to close it.

**Comment by aspadistra** [comment]
Probably a lot of developers of this program are too young to remember the history of ADA or its importance -- BEFORE JAVA IT WAS ABOUT THE ONLY SAFE PROGRAMMING LANGUAGE ! 

Other more recent attempts at safer programming languages 

1. Java Bytecode and its Android Variant ...
2. Rust, mainly now being used to fix the hopelessly not modern back ends of FIREFOX

For more reading, and the standard Wikipedia whitewash to cover up how dangerous it has been not having most things programmed in it ...
[https://en.wikipedia.org/wiki/Ada_(programming_language)](url)
