### ISSUE TITLE
There are two klein.resource's

### ISSUE THREAD

**Issue by wsanchez** [twisted/klein#224]
There are two `klein.resource`'s:
 * The symbol defined in `klein/__init__.py`
 * The module `klein.resource`

Which means such great things as:

```console
>>> import klein.resource
>>> from klein import resource as resource
>>> resource
<module 'klein.resource' from '/Users/wsanchez/Dropbox/Developer/Twisted/klein/.tox/coverage-py36-twcurrent/lib/python3.6/site-packages/klein/resource.py'>
>>> 
```

and

```console
>>> from klein import resource as resource
>>> resource
<bound method Klein.resource of <klein._app.Klein object at 0x10cb359e8>>
>>> 
```

**Comment by wsanchez** [comment]
Doing a GitHub search, [72 python files reference `KleinResource`](https://github.com/search?utf8=✓&q=KleinResource+extension%3Apy&type=Code&ref=advsearch&l=&l=).

This is only available via the `klein.resource` module.

**Comment by wsanchez** [comment]
I found this in #223 when I added `test/test_exports.py`, which imported `klein.resource` and then `test_resource.GlobalAppTests.test_global_app` started to fail.

**Comment by wsanchez** [comment]
In #223, I've removed the `resource` symbol from `__init__.py`.

This seems like the least-worst solution here; removing the `klein.resource` module looks to be more disruptive, and current users of the imported symbol are subject to surprise breakage as it is.

**Comment by wsanchez** [comment]
#225 is a PR that fixes this specifically.

**Comment by glyph** [comment]
Just curious - what version of Python did you run your reproducer on?

**Comment by wsanchez** [comment]
I can reproduce the initial report using `./.tox/coverage-py36-twcurrent/bin/python`.  Also `./.tox/coverage-pypy-twcurrent/bin/python`.

Note that you have to exit the interpreter between the two tests:

```console
>>>> import klein.resource
>>>> from klein import resource as resource
>>>> resource
<module 'klein.resource' from '/Users/wsanchez/Dropbox/Developer/Twisted/klein/.tox/coverage-pypy-twcurrent/site-packages/klein/resource.pyc'>
>>>> from klein import resource as resource
>>>> resource
<module 'klein.resource' from '/Users/wsanchez/Dropbox/Developer/Twisted/klein/.tox/coverage-pypy-twcurrent/site-packages/klein/resource.pyc'>
```

¡Yay!
