### ISSUE TITLE
Reconsider combined usage of bytes and text in new headers API.

### ISSUE THREAD

**Issue by wsanchez** [twisted/klein#227]
The [new headers API ](https://github.com/twisted/klein/blob/master/src/klein/_headers.py) allows headers to be accessed and set using either bytes or text for the header names, as long as the same type is returned or provided for corresponding values.

@moshez points out that this is icky and suggests that we use separate API for bytes and text, instead of having this polymorphism.

The polymorphic API follows the pattern used by [twisted.web.http_headers.Headers](http://twistedmatrix.com/documents/current/api/twisted.web.http_headers.Headers.html) does.

This ticket is here to solicit input on the path forward.

**Comment by wsanchez** [comment]
For example:
```python
IHTTPHeaders.getValues(AnyStr) ➜ Iterable(AnyStr)
```
takes bytes or text and returns bytes or text, respectively.  It could be replaced with:
```python
IHTTPHeaders.getValues(Text) ➜ Iterable(Text)
IHTTPHeaders.getBytesValues(bytes) ➜ Iterable(bytes)
```

We can similarly replace
```python
IMutableHTTPHeaders.addValue(AnyStr, AnyStr) ➜ None
```
with
```python
IMutableHTTPHeaders.addValue(Text, Text) ➜ None
IMutableHTTPHeaders.addBytesValue(bytes, bytes) ➜ None
```

**Comment by wsanchez** [comment]
Note that I'm favoring the text access above (text gets `addValue` rather than `addTextValue`), because I think that the majority of uses cases want text.

**Comment by wsanchez** [comment]
Another case is that we allow text pairs in the `rawValues` argument to `normalizeRawHeadersMutable`, which by extension also means to the `__init__` methods for `FrozenHTTPHeaders` and `MutableHTTPHeaders`.  It's fairly permissive:

```python
headers = FrozenHTTPHeaders(
    (u"Content-Type", u"text/html; charset=utf-8"),
    (b"ETag", b"yo"),
    (u"X-Fubar", binary_crap_omg),  # for the haters
)
```

The final value for `headers.rawHeaders` will be tuples of bytes, so having the `__init__` argument not accept that is weird.  But since I think the common case for the caller is to use text, forcing the caller to encode (to Latin 1) seems unfortunate.  Adding factory methods (`fromTextPairs`, `fromBytesPairs`) would work.

**Comment by wsanchez** [comment]
All that said, at PyCon '17, people seemed OK with the polymorphic API here.

**Comment by wsanchez** [comment]
@moshez I think you had opinions

**Comment by twm** [comment]
FWIW as a prospective user of the new API I am fine with either style in the abstract. Some miscellaneous thoughts:

* It certainly _is_ useful (as in, I have used it) to be able to reference headers as both text and bytes, but I cannot think of a time I've not known which I wanted when e.g. calling `getRawValues()`. In that sense separate text/bytes accessor APIs would be fine.
* I haven't looked at the implementation, so please forgive me if this is uncalled for, but I want to be sure that the `t.w.http_headers.Headers` mistake of interpreting header values as UTF-8 isn't repeated.
* I absolutely have (with `t.w.h.Headers`) and will want to be able to construct `FrozenHTTPHeaders` with a mix of text and bytes. If this implies the polymorphic API, then so should it be.

**Comment by glyph** [comment]
I am in favor of leaving the combined str/bytes behavior in place.  While I realize that it might encourage a certain sort of sloppiness under certain conditions, there's also the fact that as long as we're bridging the 2/3 gap, there will exist cases where we want it to behave as a collection of *str*s (i.e.: not text, not bytes), where headers are mapped to Python identifiers, for example.  Which means either we keep it as-is, or we add a third method, `IHTTPHeaders.getStrValues`, which semi-permanently adds a bunch of gross API surface to bridge this gap, instead of allowing it to implicitly exist.

**Comment by wsanchez** [comment]
@twm You can absolutely construct headers with a mix of bytes and text.  The only thing to be careful of is that if you want to read bytes from or write bytes into a header value, that you have to specify the header name in bytes as well.

It sounds to me like the polymorphic API is useful as-is.  There may still be an argument for an explicit API, but the polymorphic API doesn't exclude that possibility.

I'm going to close this, since there's no change needed at the moment, and adding the explicit API can wait for a new ticket if it's wanted.
