### ISSUE TITLE
Add a startup hook

### ISSUE THREAD

**Issue by wsanchez** [twisted/klein#243]
Sometimes you need to set some things up before you can handle any requests, such as loading up your initial data schema or something.

It would be nice to have a hook for performing some (possibly async) stuff when the app starts up, but blocking requests until the startup hook is complete.

**Comment by notoriousno** [comment]
Is there really a need for a "hook"? It would be better to do what `autobahn` does and have another function that simply doesn't execute `reactor.run()`. Then it'll be trivial to run the server after all other async tasks are complete.

**Comment by glyph** [comment]
I’m inclined to agree with @notoriousno here; perhaps if we had some more structured startup, like a `twist klein` plugin, an explicit setup hook might be useful in that, but with our current infrastructure it feels like you can easily just call the function yourself...

**Comment by wsanchez** [comment]
OK
