### ISSUE TITLE
Exceptions raised in @app.route-decorated functions are passed to log.err twice

### ISSUE THREAD

**Issue by philmayers** [twisted/klein#25]
The "processing_failed" function calls log.err on any exception:

https://github.com/twisted/klein/blob/master/klein/resource.py#L125

~~...but it also calls t.web Request.processingFailed which _also_ calls log.err:~~

~~https://github.com/twisted/twisted/blob/trunk/twisted/web/server.py#L314~~

But the failure is also passed to log.err when the Deferred is garbage-collected.

This means errors/tracebacks are logged twice - not useful.

**Comment by brighid** [comment]
No comment from reporter: this probably is safe to close.
