### ISSUE TITLE
How to overcome cors issues?

### ISSUE THREAD

**Issue by SharedMocha** [twisted/klein#250]
Can you please share samples on how to overcome cors issue?
I am looking at how we need to set header requests in routes

**Comment by notoriousno** [comment]
This is more of a generic topic and information about CORS is readily available on the web. If you're having specific questions please ask a detailed question on [Stackoveflow](https://stackoverflow.com/questions/tagged/twisted).

**Comment by vaughansharman** [comment]
Reopening this, as far as I can see there is no documentation on configuring Klein to work with CORS.

i.e. calling a Klein API from a browser with out of the box config fails... I have given up and just moved to use flask. But this is probably a problem for many...
