### ISSUE TITLE
can't bind a Klein app to an object with a "blank" class-level descriptor (breaking `trial -j`)

### ISSUE THREAD

**Issue by glyph** [twisted/klein#257]
Consider the following:

```python3
from klein import Klein

class ClassProperty(object):
    def __get__(self, oself, owner):
        raise AttributeError("you just don't have that special something")

class Oddment(object):
    __something__ = ClassProperty()
    router = Klein()

Oddment().router.resource()
```

This fails because `Klein.__get__` is attempting to find *itself* on Oddment, to give itself a name.  It doesn't care about `__something__` and it should ignore the (totally valid) `AttributeError`.

----

Why do I know this and why do I care?

It turns out that `__provides__` turns into a descriptor like `__something__` when run in a `trial -j` execution context.

In the parent process, something about test discovery causes every test instance to get adapted to `ITestCase` which fills out the cache.  But, in `-j` mode, discovery happens in the parent but execution happens in the child, which means the child-process test cases don't get adapted in this way.  So if you:

- use `router` objects on `TestCase` subclasses, bound to those `TestCase` instances
- run your tests with `trial -j`

Klein blows up.

**Comment by markrwilliams** [comment]
Should there also be a bug against trial?  It seems like the lack of adaptation in the worker processes might lead to other strange problems.

**Comment by glyph** [comment]
@markrwilliams I don't think that this is a Trial bug; this is a perfectly valid way for a class to behave.  To that point - what would the bug be exactly?  How would trial ensure this property is met?

If anything it's a bug that ought to be filed against Zope Interface :).
