### ISSUE TITLE
Drop support for Python 3.4

### ISSUE THREAD

**Issue by wsanchez** [twisted/klein#279]
I'd like us to consider dropping support for Python 3.4.

Some reasons:
 * [Twisted dropped support for Python 3.4](https://github.com/twisted/klein/pull/275)
 * [It prevents us from updating hypothesis to 4.15](https://travis-ci.org/twisted/klein/builds/518991027?utm_source=github_status&utm_medium=notification)
 * It removes 3 of our Travis tasks
 * Anything Python 3 less than 3.6 is weak salsa

**Comment by glyph** [comment]
> * Anything Python 3 less than 3.6 is weak salsa

PyPy 3.6 is sadly still "alpha" 😢

**Comment by glyph** [comment]
That said: I'm on board. ~Nobody seems to use 3.4 whereas lots of people use 3.5,6,7.

**Comment by wsanchez** [comment]
Good news: Our pypy support currently is for pypy3.5 so while I won't write the "let's kill 3.5" ticket for a while, dropping 3.4 doesn't really effect our pypy testing.

**Comment by wsanchez** [comment]
#278 is dropping support.  We can back that (and the hypothesis update) out someone wants to talk us out of dropping 3.4.

**Comment by hugovk** [comment]
Python 3.4 has very low usage.

Here's the pip installs for klein from PyPI for March 2019:

| category | percent | downloads |
|----------|--------:|----------:|
|      2.7 |  51.39% |    27,110 |
|      3.6 |  38.98% |    20,563 |
|      3.7 |   4.39% |     2,318 |
|      3.5 |   4.17% |     2,201 |
| null     |   0.71% |       375 |
|      3.4 |   0.27% |       142 |
|      2.6 |   0.07% |        38 |
|      3.8 |   0.01% |         3 |
| Total    |         |    52,750 |

Source: `pypistats python_minor klein --last-month # pip install pypistats`

See https://dev.to/hugovk/python-version-share-over-time-4-26hm for stats for other projects, also with very low 3.4 numbers.

**Comment by glyph** [comment]
Anybody want to write a PR?

**Comment by hugovk** [comment]
#278 drops Python 3.4 along with other changes, and please see #284 that only drops 3.4 support.

**Comment by wsanchez** [comment]
Fixed by #278
