### ISSUE TITLE
what can we do to improve the performace tests?

### ISSUE THREAD

**Issue by liuzhijun** [twisted/klein#295]
Based on the result:
https://www.techempower.com/benchmarks

for example, can we replace the jinja2?
any suggestions?

**Comment by ldanielburr** [comment]
The short and relatively useful answer is: run Klein under Pypy.  A longer answer is: profile Klein and Twisted for performance bottlenecks and implement optimizations, in Python or in Cython as needed.

Realistically though, the only Python frameworks that post big numbers on the TechEmpower benchmarks are the ones that wrap libuv for the event loop and wrap an HTTP parser written in C.  Templating has virtually no impact on performance compared to those things.

**Comment by liuzhijun** [comment]
Thank you !
