### ISSUE TITLE
NOT_DONE_YET comparison warning

### ISSUE THREAD

**Issue by arnimarj** [twisted/klein#296]
It seems that https://github.com/twisted/klein/blob/master/src/klein/_resource.py#L278 is doing a value comparison with `NOT_DONE_YET`, similarly to twisted.web in https://twistedmatrix.com/trac/ticket/9597

I get these warning regularly: `BytesWarning: Comparison between bytes and int` when running in bytes-warning mode (`-b`)

**Comment by itamarst** [comment]
Still a problem, although the line number has changed: https://github.com/twisted/klein/blob/022a25adc2056aa9c09ad352c42d381a04f7401a/src/klein/_resource.py#L300
