### ISSUE TITLE
DecodedURL missing ?!? but installed

### ISSUE THREAD

**Issue by peterus** [twisted/klein#336]
I installed buildbot-badges for buildbot. it has a dependency on klein and klein has a dependency to hyperlink.

But buildbot is giving me this error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/buildbot/plugins/db.py", line 214, in _load_entry
>     result = entry.load()
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2444, in load
>     return self.resolve()
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2450, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/home/buildbot/.local/lib/python3.6/site-packages/buildbot_badges/__init__.py", line 20, in <module>
>     from klein import Klein
>   File "/usr/local/lib/python3.6/dist-packages/klein/__init__.py", line 5, in <module>
>     from ._app import Klein, handle_errors, route, run, urlFor, url_for
>   File "/usr/local/lib/python3.6/dist-packages/klein/_app.py", line 34, in <module>
>     from ._interfaces import IKleinRequest
>   File "/usr/local/lib/python3.6/dist-packages/klein/_interfaces.py", line 13, in <module>
>     from ._imessage import (
>   File "/usr/local/lib/python3.6/dist-packages/klein/_imessage.py", line 16, in <module>
>     from hyperlink import DecodedURL
> ImportError: cannot import name 'DecodedURL'

pip installed this packages automaticaly:

> buildbot@buildbot:~/master$ pip3 install buildbot-badges
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: buildbot-badges in /home/buildbot/.local/lib/python3.6/site-packages (2.7.0)
> Requirement already satisfied: CairoSVG in /usr/local/lib/python3.6/dist-packages (from buildbot-badges) (2.4.2)
> Requirement already satisfied: cairocffi in /usr/local/lib/python3.6/dist-packages (from buildbot-badges) (1.1.0)
> Requirement already satisfied: klein in /usr/local/lib/python3.6/dist-packages (from buildbot-badges) (19.6.0)
> Requirement already satisfied: Jinja2 in /usr/lib/python3/dist-packages (from buildbot-badges) (2.10)
> Requirement already satisfied: defusedxml in /usr/local/lib/python3.6/dist-packages (from CairoSVG->buildbot-badges) (0.6.0)
> Requirement already satisfied: tinycss2 in /usr/local/lib/python3.6/dist-packages (from CairoSVG->buildbot-badges) (1.0.2)
> Requirement already satisfied: cssselect2 in /usr/local/lib/python3.6/dist-packages (from CairoSVG->buildbot-badges) (0.2.2)
> Requirement already satisfied: pillow in /usr/local/lib/python3.6/dist-packages (from CairoSVG->buildbot-badges) (7.0.0)
> Requirement already satisfied: cffi>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from cairocffi->buildbot-badges) (1.14.0)
> Requirement already satisfied: setuptools>=39.2.0 in /usr/local/lib/python3.6/dist-packages (from cairocffi->buildbot-badges) (45.1.0)
> Requirement already satisfied: incremental in /usr/lib/python3/dist-packages (from klein->buildbot-badges) (16.10.1)
> Requirement already satisfied: six in /usr/lib/python3/dist-packages (from klein->buildbot-badges) (1.11.0)
> Requirement already satisfied: typing in /usr/local/lib/python3.6/dist-packages (from klein->buildbot-badges) (3.7.4.1)
> Requirement already satisfied: hyperlink in /usr/lib/python3/dist-packages (from klein->buildbot-badges) (17.3.1)
> Requirement already satisfied: zope.interface in /usr/lib/python3/dist-packages (from klein->buildbot-badges) (4.3.2)
> Requirement already satisfied: Tubes in /usr/local/lib/python3.6/dist-packages (from klein->buildbot-badges) (0.2.0)
> Requirement already satisfied: Twisted>=15.5 in /usr/lib/python3/dist-packages (from klein->buildbot-badges) (17.9.0)
> Requirement already satisfied: Werkzeug in /usr/local/lib/python3.6/dist-packages (from klein->buildbot-badges) (1.0.0)
> Requirement already satisfied: attrs in /usr/lib/python3/dist-packages (from klein->buildbot-badges) (17.4.0)
> Requirement already satisfied: webencodings>=0.4 in /usr/local/lib/python3.6/dist-packages (from tinycss2->CairoSVG->buildbot-badges) (0.5.1)
> Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi>=1.1.0->cairocffi->buildbot-badges) (2.19)
> Requirement already satisfied: characteristic in /usr/local/lib/python3.6/dist-packages (from Tubes->klein->buildbot-badges) (14.3.0)

any ideas how to fix this?

**Comment by peterus** [comment]
found out that my pre-installed version of hyperlink was 17.0.0 and pip is not updating it automatically. installed now the newest version manually and issue is gone.

**Comment by laf0rge** [comment]
shouldn't klein explicitly depend on a certain minimum version of hyperlink, i.e. a version that already contains DecodedURL?

**Comment by laf0rge** [comment]
I'm just running into this on a stock Debian 10 system with python3-hyperlink installed from a debian package, and then trying to install klein with pip3.  Apparently klein setup.py is happy with hyperlink 17.3.1 but then uses something that version doesn't provide?

**Comment by wsanchez** [comment]
If you can ID the minimum version of hyperlink that works, I'm happy to add that to requirements.
