### ISSUE TITLE
Re-connect requires.io using a different account

### ISSUE THREAD

**Issue by exarkun** [twisted/klein#358]
Apparently I set up requires.io for klein some while ago?  I don't recall, but my name on https://github.com/twisted/klein/pull/356 and other sure seems to suggest this.  I didn't realize I was such a prolific klein contributor!  Nevertheless, I don't actively contribute to klein these days and I'd rather see this connection done without using my github account.

I'm not sure if requires.io still requires a user account or if they've adopted one of the other github integration strategies.  Does someone want to volunteer their account, or to investigate other options?

I don't have a lot of bandwidth to help with this myself.  I'll try not to rush anyone of this but I would like the change made.  Therefore, I won't break this association myself until at least July 1st.

**Comment by wsanchez** [comment]
@exarkun Feel free to detach yourself from it and when you are done, I'll set it back up.

There's no real harm in doing so; a delay in getting updates from `requires.io` is no big deal.

**Comment by exarkun** [comment]
Great, thanks for the quick response.  I ... think ... I've revoked the access on my side now.

**Comment by wsanchez** [comment]
Well I think I've set it up, will see if it sends any PRs now.

Note I'd like to try out to [Dependabot](https://dependabot.com) here but https://github.com/dependabot/feedback/issues/783
