### ISSUE TITLE
Remove unused private type aliases

### ISSUE THREAD

**Issue by wsanchez** [twisted/klein#414]
We have a number of type aliases that are defined by never used.

 * In `_session.py`:
    * `_procureProcurerType`
    * `_kleinRenderable = Any`, which is too broad, and we have a public `KleinRenderable` in `_app.py` now.
    * `_routeCallable`
    * `_kleinCallable`, which smells a bit like `KleinRoute`
    * `_kleinDecorator`
    * `_requirerResult`

 * In `_form.py`
    * `_requirerFunctionWithForm`
    * `_routeCallable = Any`, see above
    * `_routeDecorator` - this one is used, and maybe should be moved to join the public team
    * `_validationFailureHandler`

It's hard to verify that these types are correct when they aren't being used, so my inclination is to remove them until such time as they are actually needed.

**Comment by wsanchez** [comment]
@glyph FYI; I think this Is your code

**Comment by glyph** [comment]
Yep get rid of 'em all, no compat constraints, just 🔥
