### ISSUE TITLE
Enable Read-The-docs pull builds

### ISSUE THREAD

**Issue by wsanchez** [twisted/klein#459]
@adiroiban says:

> maybe also enable Read The Docs pull builds. Let me know if you need help wit that ... or ask Thomas over IRC for help.

I didn't want to hold the PR this comment was made in, but we should do that.

**Comment by adiroiban** [comment]
Only @glyph or @hawkowl can change the Read The Docs Settings - https://readthedocs.org/projects/klein/  see Maintainers

**Comment by glyph** [comment]
@wsanchez @adiroiban I just added both of you.

**Comment by adiroiban** [comment]
I have enabled the PR builds for read the docs.

I think that this issue can be closed by a PR in which an explicit read the docs configuration file is created into the repo and `tox -e docs` is updated to run `sphinx-build` with `-W --keep-going`

**Comment by wsanchez** [comment]
Great. I wouldn't mind learning how to do that so I'll bug you and Thomas about it later. Thanks, Adi.
