### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [twisted/klein#494]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine src/klein/_decorators.py and observe `unconditinally`, however expect to see `unconditionally`.
- Examine src/klein/_form.py and observe `interable`, however expect to see `iterable`.
- Examine src/klein/_session.py and observe `dependnecy`, however expect to see `dependency`.
- Examine src/klein/test/test_form.py and observe `attempst`, however expect to see `attempts`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/klein/pull/new/bugfix_typos

Thanks.

**Comment by wsanchez** [comment]
@timgates42 A PR would be great, thanks!

**Comment by timgates42** [comment]
Thanks @wsanchez added one
