### ISSUE TITLE
Documentation on readthedocs.io is not being updated

### ISSUE THREAD

**Issue by itamarst** [twisted/klein#537]
For example, https://github.com/twisted/klein/commit/df72fd242d121743a78a35caae68fd01fd6ab338 is in release 21.8, but the documentation page (https://klein.readthedocs.io/en/latest/examples/handlingpost.html) still has the old version.

**Comment by Julian** [comment]
Looks like the only build within the last 2 years failed on RTD: https://readthedocs.org/projects/klein/builds/13053528/

**Comment by glyph** [comment]
Builds should work now, I think.
