### ISSUE TITLE
no contact info?

### ISSUE THREAD

**Issue by EdStauff** [twisted/klein#557]
I apologize for submitting this as a bug, but it's the only way I could find to communicate with the development team – and that's the bug:

I couldn't find any way to ask questions about klein. 

In the interest of saving time, here's the question I wanted to ask:
Why is version 16.12 (Dec 13 2016) the latest version available here, but libraries.io has version 21.8.0 (Aug 8 2021)?

**Comment by glyph** [comment]
Questions are a perfectly fine kind of issue, particularly if there's no other contact form, so don't feel bad.

What do you mean by "available here"? The official source of truth is PyPI, which has 21.8.0: https://pypi.org/project/klein/#history / https://pypi.org/project/klein/21.8.0/

We've also tagged 21.8.0.

I guess you mean the github "releases" mechanism?  I think that was a failed experiment with a different release process which never really got documented.  I guess we should pull all of those so we don't have a misleading history there, but it seems like that might break something.
