### ISSUE TITLE
Why "405 Method Not Allowed" ?

### ISSUE THREAD

**Issue by gus4rs** [twisted/klein#579]
I am debugging a large app using Klein and twisted that is failing to respond correctly, that declares the following route:

```python
@app.route('/session', methods=['GET'])
def session(self, request):
    ...
```

Every request to this route returns 405, even GET ones. If I remove the methods

```python
@app.route('/session')
```

it works fine.

Python 3.11.2
klein: 21.8.0
twisted: 22.8.0
Linux Fedora 37

Any clues?

**Comment by gus4rs** [comment]
this is a small reproducer

```python
from klein import Klein

api_version_string = "/api/v1"

class Service:
    app = Klein()

    @app.route('/', branch=True, methods=['OPTIONS'])
    def preflight(self, request):
        request.setHeader("Access-Control-Allow-Origin", "*")
        request.setHeader("Access-Control-Allow-Methods", "POST")

    with app.subroute(api_version_string) as app:
        @app.route('/session', methods=['GET'])
        def session(self, request):
            return 'Hello, world!'


if __name__ == "__main__":
    svc = Service()
    svc.app.run('localhost', 8080)
```

**Comment by gus4rs** [comment]
Even smaller:

```python
from klein import run, route

@route('/', methods=['GET'])
def do_post(request):
    return "hello" 

run("localhost", 8080)
```


When calling it, I get

```
$curl  http://localhost:8080/
<!doctype html>
<html lang=en>
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

But if I remove the ```methods``` it works.


Questions:

1. Did this methods behaviour change over time, so that the sample used to work and now it doesn't?
2. What is the correct way of using it?

**Comment by gus4rs** [comment]
Closing this in favour of https://github.com/pallets/werkzeug/issues/2676

**Comment by gus4rs** [comment]
Reopening since werkzeug thinks it is a klein issue

**Comment by gus4rs** [comment]
Easy way to reproduce:

Create ```app.py```:
```
from klein import run, route

@route('/', methods=['GET'])
def do_post(request):
    return "hello"

run("localhost", 8080)
```

Run it in a virtual env:

```
python3 -m venv repro
source repro/bin/activate
pip install klein
python app.py 
```
Call it:

```
curl http://localhost:8080
```

You will get 405 error, because the version of werkzeug pulled is 2.3.2

If you downgrade werkzeug to 2.2.0 with ``` pip install werkzeug==2.2.0``` and re-run the app, it works!


I reported it to werkzeug and the snowflakes over there closed the issue and marked my answers as abuse, even if I proved something changed in version 2.3.0 onwards of their code that broke this very simple use case. Go figure...

**Comment by itamarst** [comment]
This is fixed in the HEAD, going to try to do a new release next.

**Comment by itamarst** [comment]
New release is out, should be fixed.
