### ISSUE TITLE
ReadTheDocs is showing old version of docs

### ISSUE THREAD

**Issue by itamarst** [twisted/klein#580]
Last release was 21.8 in August 2021, Travis CI was removed from docs in April 2021, RTD still has the Travis CI mention...

**Comment by glyph** [comment]
All the builds are failing on readthedocs.org. Apparently "force push to master" is the only way to test changes to the configuration?

**Comment by glyph** [comment]
OK, I rolled my face back and forth across the keyboard until this happened 
<img width="883" alt="image" src="https://user-images.githubusercontent.com/716529/235795006-a091f86c-030c-44a7-98ac-f7740902d586.png">
