### ISSUE TITLE
Any way to do send_file like Flask

### ISSUE THREAD

**Issue by electroniccc** [twisted/klein#690]
I need to send a file in POST handler. But I can't find a method to do this. Is there any way to send a file?
Just like this:
```python
@route("/", methods=["POST"])
def handler(request):
  # do sth.
  return send_file(request, filename, file_path)
```

**Comment by glyph** [comment]
The very first example in the documentation is exactly this. Have a look at the docs here: https://klein.readthedocs.io/en/latest/examples/staticfiles.html
