### ISSUE TITLE
[QUESTION] is it possible / easy to add a klein application to an existing twisted.application.service.Application?

### ISSUE THREAD

**Issue by michelcrypt4d4mus** [twisted/klein#753]
Apologies if this is the wrong place to ask this but is it possible / easy to add a `klein` application to an existing `Twisted` app launched via a `.tac` file? I found [this part of the docs](https://klein.readthedocs.io/en/latest/examples/twistd.html) which explain how to implement a `klein` app and launch it via `twistd -n web` so it seems like it should be possible to do what i describe - create a `klein` resource and add it to the `Application` via `setServiceParent()` - but I'm unclear as to how to proceed given that the documentation example assumes that `klein` is the entire application whereas my use case requires me to manage other resources listening on other ports.

thanks.

**Comment by michelcrypt4d4mus** [comment]
managed to work this one out far more easily than i expected... for future searchers:

### `klein_server.py`
```python
from klein import resource, route
from twisted.application import internet
from twisted.web.server import Site


@route('/')
def hello(request):
    return "Hello, world!"


def getService():
    return internet.TCPServer(7757, Site(resource()), interface='')
```

### `app.tac`
```python
from klein_server import get_service

application = service.Application(f"illmaticized")
getService().setServiceParent(application)
```

Run with `twistd -noy app.tac`.

**Comment by glyph** [comment]
Awesome, glad you were able to quickly figure this out. Is there still a doc issue here though, where it could have been made clearer, so you wouldn't have gotten stuck in the first place?

**Comment by michelcrypt4d4mus** [comment]
it definitely wasn't super clear. i was able to figure it out by looking at the [`run()`](https://github.com/twisted/klein/blob/1fa3d7098bed7802fcd9f45eb21ddc07108dfda2/src/klein/_app.py#L677) method and seeing how the `Site` object wraps a call to `resource()` much the same as some twisted code i was already working with.

didn't seem well documented (or maybe I missed it) that you can launch a standalone `klein` server outside of the `twistd` CLI tool or the `klein` runner by calling  `internet.TCPServer(7757, Site(resource()), interface='')`.

maybe a line in the page of the docs i linked pointing that out might prove fruitful for someone else in the future.

**Comment by glyph** [comment]
@michelcrypt4d4mus I filed https://github.com/twisted/klein/issues/757 to try to add something to the documentation so others don't experience this as badly.
