### ISSUE TITLE
middleware support

### ISSUE THREAD

**Issue by sunkencity** [twisted/klein#76]
I'm thinking about adding a way to add middleware to a klein app. 

I suppose this would hook into KleinResource.render? or is there some way to do this higher up in twisted already?

In middleware it would be nice to be able to add methods and instance variables to the request: Example log bound with request UUID prefix to be able to piece together all log messages that belong to a particular request (like done with thread local globals in other frameworks)

Another use is to perform generic authoriziation and return an early auth error.

This can of be done today by adding decorators but it would be nice not to have to add decorators to all routes.

Thoughts?

**Comment by brighid** [comment]
I'm also running into this—I'm working on an API, and putting in authentication and rate-limiting layers is rather cumbersome. :+1:

**Comment by wsanchez** [comment]
This is a pretty broad request, so it's not entirely actionable.  "Middleware" can mean anything.  Perhaps you could restate this as a few specific feature requests.

**Comment by glyph** [comment]
I'm inclined to agree with @wsanchez here. This is probably a desirable end-state in some sense but it's a bit too vague.  What does "cumbersome" mean?  Shouldn't klein just do sessions and rate-limiting internally? (it will: #134 )

Please feel free to open lots of more specific issues :).
