### ISSUE TITLE
How to host a klein based service?

### ISSUE THREAD

**Issue by coldfix** [twisted/klein#77]
Hey,

Suppose I have a klein based application which I'd like to deploy on a web server. Of course, the application shouldn't run as root and it should be automatically launched whenever the server is started (or at least when it's requested). Optionally, it would be great to run the app inside a virtualenv. What's the generic way to accomplish this?

I'd guess there is something you could do with `twistd` but in a quick search I couldn't find anything sufficiently easy for my level of expertise (=zero).

I think a few sentences about this in the documentation would do neatly. Apologies if I somehow overlooked the corresponding section.

Best regards,
Thomas

**Comment by hawkowl** [comment]
Hi, does http://klein.readthedocs.org/en/latest/examples/twistd.html help at all? There's an example for starting twistd using systemd here too: http://twisted.readthedocs.org/en/twisted-15.2.1/core/howto/systemd.html?highlight=systemd#create-a-systemd-service-file . Instead of `/usr/bin/twistd`, just have it to the bin in the virtualenv (so `pathtovenv/bin/twistd`).

**Comment by coldfix** [comment]
Thanks. I had already seen these resources, but your answer still helped convincing me to do the work: My webserver doesn't run on systemd, and I wanted to check if there is an easier way before writing an initscript (which I wasn't very eager to dive into).

Might I suggest to add a link to the twisted deployment info in the klein docs?

For anyone without prior experience it might be useful to include a template somewhere in the documentation. My initscript looks as follows (for debian wheezy, not sure if that matters):

```bash
#!/bin/bash

DAEMON=myapp

[ -f /lib/lsb/init-functions ] && . /lib/lsb/init-functions
[ -f /etc/default/rcS ]        && . /etc/default/rcS
[ -f /etc/conf.d/$DAEMON ]     && . /etc/conf.d/$DAEMON

if ! [ -x $TWISTD ]; then
	log_warning_msg "$TWISTD not available. exiting."
fi

ARGS=(web --class $RESOURCE --port $PORT)
mkdir -p $RUNPATH
chown $USER:$USER $RUNPATH
cd $RUNPATH

if [ -f twistd.pid ]; then
	PID=$(cat twistd.pid)
else
	PID=
fi

case "$1" in
 start)
   if ! [ -z $PID ]; then
     log_warning_msg "$DAEMON already running as $PID."
     exit 0;
   fi
   log_daemon_msg "Starting $DAEMON"
   if sudo -u $USER $TWISTD ${ARGS[@]} &>/dev/null; then
     log_end_msg 0
   else
     log_end_msg 1
   fi
   ;;

 stop)
   if [ -z $PID ]; then
     log_warning_msg "$DAEMON not running."
     exit 0;
   fi
   log_daemon_msg "Stopping $DAEMON"
   if kill $PID; then
     log_end_msg 0
   else
     log_end_msg 1
   fi
   ;;

 restart)
   if ! [ -z $PID ]; then
     $0 stop
   fi
   $0 start
   ;;

 *)
   echo "usage: $0 {start|stop|restart}"  
esac
```

and you'd define the settings in `/etc/conf.d/myapp`, e.g.:

```bash
TWISTD=/home/myapp/env/bin/twistd
RUNPATH=/home/myapp
RESOURCE=myapp.resource
USER=myapp
PORT=8080
```

In case you're experienced with this setup, I'd appreciate any tipps you might have to improve/simplify my solution. Otherwise, feel free to close this issue. Thanks for your reply.

Best regards,
Thomas

**Comment by sunkencity** [comment]
My suggestion is to look at supervisord. 

https://www.digitalocean.com/community/tutorials/how-to-install-and-manage-supervisor-on-ubuntu-and-debian-vps

It handles all the jazz of starting as a specific user, logs, restarting and more.

**Comment by coldfix** [comment]
Oh that looks great, thanks for the tipp!
