### ISSUE TITLE
Debian / Ubuntu packaging

### ISSUE THREAD

**Issue by evilaliv3** [twisted/klein#95]
I was looking at the maturity of the project to evaluate its use in https://github.com/globaleaks/GlobaLeaks as replacement for cyclone and i found strange that the librrary regardless of the good results obtained is still not packaged in Debian / Ubuntu.

This ticket is to keep track of such activity.

I see that the process of packagin klein has been started in 2014 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=738156) but i think no progress has been done.

@hawkowl can you clarify on the status so that eventually i will try to help on this front?

**Comment by hawkowl** [comment]
I am not sure about how this is done, cc @mithrandi (who is a Debian-y person).

**Comment by hawkowl** [comment]
(worth noting, we generally discourage using the Debian-packaged versions of Twisted, or any other Python software -- sometimes they apply patches, so we end up with wacky new bugs/bugs not appearing when they should/completely broken software [like in pip's case]. So I'm not sure if we *want* to... hmm.)

**Comment by irl** [comment]
You can probably close this issue.

https://packages.debian.org/search?keywords=klein

**Comment by mithrandi** [comment]
Thanks!
